### ISSUE TITLE
Adding an empty tag crashes the app

### ISSUE THREAD

**Issue by melvin4u445** [ARK-Builders/ARK-Navigator#101]
**Steps:**
1. Open an image
2. Click the pen button to add a tag
3. When the "Input comma-separated tags" modal appears, press the done button without typing anything

App crashes

```
10-09 20:25:24.948 15609 15609 E AndroidRuntime: FATAL EXCEPTION: main
10-09 20:25:24.948 15609 15609 E AndroidRuntime: Process: space.taran.arknavigator, PID: 15609
10-09 20:25:24.948 15609 15609 E AndroidRuntime: java.lang.AssertionError: No tag can be empty
10-09 20:25:24.948 15609 15609 E AndroidRuntime: 	at space.taran.arknavigator.utils.Converters$Companion.tagsFromString(Tags.kt:23)
10-09 20:25:24.948 15609 15609 E AndroidRuntime: 	at space.taran.arknavigator.ui.fragments.GalleryFragment.showEditTagsDialog$lambda-6(GalleryFragment.kt:289)
10-09 20:25:24.948 15609 15609 E AndroidRuntime: 	at space.taran.arknavigator.ui.fragments.GalleryFragment.lambda$MdOFS114x7i8IC1Lrf73INcu_dA(Unknown Source:0)
10-09 20:25:24.948 15609 15609 E AndroidRuntime: 	at space.taran.arknavigator.ui.fragments.-$$Lambda$GalleryFragment$MdOFS114x7i8IC1Lrf73INcu_dA.onEditorAction(Unknown Source:9)
10-09 20:25:24.948 15609 15609 E AndroidRuntime: 	at android.widget.TextView.onEditorAction(TextView.java:6944)
10-09 20:25:24.948 15609 15609 E AndroidRuntime: 	at com.android.internal.widget.EditableInputConnection.performEditorAction(EditableInputConnection.java:138)
10-09 20:25:24.948 15609 15609 E AndroidRuntime: 	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:360)
10-09 20:25:24.948 15609 15609 E AndroidRuntime: 	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
10-09 20:25:24.948 15609 15609 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-09 20:25:24.948 15609 15609 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:216)
10-09 20:25:24.948 15609 15609 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7211)
10-09 20:25:24.948 15609 15609 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-09 20:25:24.948 15609 15609 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
10-09 20:25:24.948 15609 15609 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
10-09 20:25:25.013 15609 15609 I Process : Sending signal. PID: 15609 SIG: 9
```

**Comment by vedranqa** [comment]
Can't reproduce.
