### ISSUE TITLE
App crashed when returning to Resources Grid after resource deletion in Gallery screen

### ISSUE THREAD

**Issue by melvin4u445** [ARK-Builders/ARK-Navigator#109]
Steps:
1. Open Navigate data
2. Open an image 
3. Long-tap the delete button

```--------- beginning of crash
10-17 19:31:13.170 19569 19569 E AndroidRuntime: FATAL EXCEPTION: main
10-17 19:31:13.170 19569 19569 E AndroidRuntime: Process: space.taran.arknavigator, PID: 19569
10-17 19:31:13.170 19569 19569 E AndroidRuntime: java.lang.NullPointerException
10-17 19:31:13.170 19569 19569 E AndroidRuntime: 	at space.taran.arknavigator.mvp.model.repo.PlainResourcesIndex.remove(PlainResourcesIndex.kt:65)
10-17 19:31:13.170 19569 19569 E AndroidRuntime: 	at space.taran.arknavigator.mvp.model.repo.AggregatedResourcesIndex.remove(AggregatedResourcesIndex.kt:20)
10-17 19:31:13.170 19569 19569 E AndroidRuntime: 	at space.taran.arknavigator.mvp.presenter.GalleryPresenter$deleteResource$1.invokeSuspend(GalleryPresenter.kt:46)
10-17 19:31:13.170 19569 19569 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
10-17 19:31:13.170 19569 19569 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
10-17 19:31:13.170 19569 19569 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
10-17 19:31:13.170 19569 19569 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-17 19:31:13.170 19569 19569 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:216)
10-17 19:31:13.170 19569 19569 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7211)
10-17 19:31:13.170 19569 19569 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-17 19:31:13.170 19569 19569 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
10-17 19:31:13.170 19569 19569 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
10-17 19:31:13.200 19569 19569 I Process : Sending signal. PID: 19569 SIG: 9
```

**Comment by kirillt** [comment]
This bug still persists, but after #122 it crashes with different error:
```
11-16 18:19:25.830  4063  4063 D gallery-screen: deleting resource 1709228972
11-16 18:19:25.833  4063  4104 D tags-storage: forgetting resource 1709228972
11-16 18:19:25.860  4063  4063 D gallery-screen: path /storage/emulated/0/TEST/Frequences.jpg removed from index
11-16 18:19:26.461  4063  4084 E         : [ZeroHung]zrhung_get_config: Get config failed for wp[0x0102]
11-16 18:19:27.383  4063  4063 D main    : back pressed in MainActivity
11-16 18:19:27.383  4063  4063 D gallery-screen: [back] clicked in GalleryFragment
11-16 18:19:27.384  4063  4063 D gallery-screen: quitting from GalleryPresenter
11-16 18:19:27.412  4063  4063 D resources-screen: inflating layout for ResourcesFragment
11-16 18:19:27.424  4063  4063 I FLTAG_FM: loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
11-16 18:19:27.424  4063  4063 I FLTAG_SFM: getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
11-16 18:19:27.424  4063  4063 D FeatureFactory: loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
11-16 18:19:27.424  4063  4063 D FeatureFactory: loadFeature() new IHwSplineOverScrollerEx()
11-16 18:19:27.424  4063  4063 D HwSplineOverScrollerExImpl: initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@fde9ffc,space.taran.arknavigator.ui.activity.MainActivity@52a914c
11-16 18:19:27.425  4063  4063 D HwSplineOverScrollerExImpl: initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
11-16 18:19:27.428  4063  4063 I FLTAG_FM: loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
11-16 18:19:27.429  4063  4063 I FLTAG_SFM: getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
11-16 18:19:27.429  4063  4063 D FeatureFactory: loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
11-16 18:19:27.429  4063  4063 D FeatureFactory: loadFeature() new IHwSplineOverScrollerEx()
11-16 18:19:27.429  4063  4063 D HwSplineOverScrollerExImpl: initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@d73bfe8,space.taran.arknavigator.ui.activity.MainActivity@52a914c
11-16 18:19:27.429  4063  4063 D HwSplineOverScrollerExImpl: initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
11-16 18:19:27.461  4063  4084 E         : [ZeroHung]zrhung_get_config: Get config failed for wp[0x0102]
11-16 18:19:27.466  4063  4063 I FLTAG_FM: loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
11-16 18:19:27.466  4063  4063 I FLTAG_SFM: getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
11-16 18:19:27.466  4063  4063 D FeatureFactory: loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
11-16 18:19:27.466  4063  4063 D FeatureFactory: loadFeature() new IHwSplineOverScrollerEx()
11-16 18:19:27.466  4063  4063 D HwSplineOverScrollerExImpl: initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@f1136e7,space.taran.arknavigator.ui.activity.MainActivity@52a914c
11-16 18:19:27.466  4063  4063 D HwSplineOverScrollerExImpl: initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
11-16 18:19:27.467  4063  4063 I FLTAG_FM: loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
11-16 18:19:27.467  4063  4063 I FLTAG_SFM: getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
11-16 18:19:27.467  4063  4063 D FeatureFactory: loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
11-16 18:19:27.467  4063  4063 D FeatureFactory: loadFeature() new IHwSplineOverScrollerEx()
11-16 18:19:27.467  4063  4063 D HwSplineOverScrollerExImpl: initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@920913d,space.taran.arknavigator.ui.activity.MainActivity@52a914c
11-16 18:19:27.467  4063  4063 D HwSplineOverScrollerExImpl: initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
11-16 18:19:27.533  4063  4063 D resources-screen: view created in ResourcesFragment
11-16 18:19:27.540  4063  4063 D resources-screen: initializing ResourcesFragment
11-16 18:19:27.540  4063  4063 D main    : tab 1 selected
11-16 18:19:27.583  4063  4063 D resources-screen: resuming in ResourcesFragment
11-16 18:19:27.584  4063  4063 D tags-selector: calculating tags and selection
11-16 18:19:27.584  4063  4063 D resources-index: 4 resources returned
11-16 18:19:27.585  4063  4063 D tags-selector: tags included: []
11-16 18:19:27.585  4063  4063 D tags-selector: tags excluded: []
11-16 18:19:27.585  4063  4063 D tags-selector: tags available: []
11-16 18:19:27.585  4063  4063 D tags-selector: tags unavailable: []
11-16 18:19:27.588  4063  4063 D resources-screen: inflating options menu in ResourcesFragment
11-16 18:19:27.634  4063  4063 D resources-screen: binding view for resource 2979783909
11-16 18:19:27.645  4063  4063 D resources-screen: binding view for resource 2446863729
11-16 18:19:27.656  4063  4063 D resources-screen: binding view for resource 432412516
11-16 18:19:27.678  4063  4063 D resources-screen: binding view for resource 1709228972
11-16 18:19:27.678  4063  4063 D AndroidRuntime: Shutting down VM
11-16 18:19:27.678  4063  4063 W an.arknavigato: Accessing hidden method Lcom/msic/qarth/PatchStore;->createDisableExceptionQarthFile(Ljava/lang/Throwable;)Z (blacklist, JNI)
11-16 18:19:27.679  4063  4063 E an.arknavigato: [qarth_debug:]  get PatchStore::createDisableExceptionQarthFile method fail.
--------- beginning of crash
11-16 18:19:27.680  4063  4063 E AndroidRuntime: FATAL EXCEPTION: main
11-16 18:19:27.680  4063  4063 E AndroidRuntime: Process: space.taran.arknavigator, PID: 4063
11-16 18:19:27.680  4063  4063 E AndroidRuntime: java.lang.AssertionError: At least one of shards must yield success
11-16 18:19:27.680  4063  4063 E AndroidRuntime: 	at space.taran.arknavigator.mvp.model.repo.index.AggregatedResourcesIndex.tryShards(AggregatedResourcesIndex.kt:31)
11-16 18:19:27.680  4063  4063 E AndroidRuntime: 	at space.taran.arknavigator.mvp.model.repo.index.AggregatedResourcesIndex.getPath(AggregatedResourcesIndex.kt:15)
11-16 18:19:27.680  4063  4063 E AndroidRuntime: 	at space.taran.arknavigator.mvp.presenter.adapter.ResourcesGridPresenter.bindView(ResourcesGridPresenter.kt:57)
11-16 18:19:27.680  4063  4063 E AndroidRuntime: 	at space.taran.arknavigator.ui.adapter.ResourcesRVAdapter.onBindViewHolder(ResourcesRVAdapter.kt:24)
11-16 18:19:27.680  4063  4063 E AndroidRuntime: 	at space.taran.arknavigator.ui.adapter.ResourcesRVAdapter.onBindViewHolder(ResourcesRVAdapter.kt:12)
11-16 18:19:27.680  4063  4063 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7254)
11-16 18:19:27.680  4063  4063 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
```

This log means that we have successfully removed the resource from out index.
But we are requesting it again because `selection` in `ResourcesRVAdapter` doesn't update for unknown reason.
