### ISSUE TITLE
Fast Scroll crash

### ISSUE THREAD

**Issue by vedranqa** [ARK-Builders/ARK-Navigator#150]
App get crashed when we do fast scroll and click on tab.

**Comment by mdrlzy** [comment]
Log:
```
2021-11-30 18:13:23.861 21261-21261/space.taran.arknavigator D/tags-selector: including tag snow
2021-11-30 18:13:23.861 21261-21261/space.taran.arknavigator D/tags-selector: calculating tags and selection
2021-11-30 18:13:23.861 21261-21261/space.taran.arknavigator D/resources-index: 1427 resources returned
2021-11-30 18:13:23.866 21261-21261/space.taran.arknavigator D/tags-selector: tags included: [snow]
2021-11-30 18:13:23.866 21261-21261/space.taran.arknavigator D/tags-selector: tags excluded: []
2021-11-30 18:13:23.866 21261-21261/space.taran.arknavigator D/tags-selector: tags available: []
2021-11-30 18:13:23.866 21261-21261/space.taran.arknavigator D/tags-selector: tags unavailable: [camp, lnkdin, van, pec, vitlo, off-road]
2021-11-30 18:13:23.934 1458-5431/? W/NotificationService: Toast already killed. pkg=space.taran.arknavigator callback=android.app.ITransientNotification$Stub$Proxy@a7278df
2021-11-30 18:13:23.944 21261-21261/space.taran.arknavigator D/AndroidRuntime: Shutting down VM
2021-11-30 18:13:23.945 21261-21261/space.taran.arknavigator E/AndroidRuntime: FATAL EXCEPTION: main
    Process: space.taran.arknavigator, PID: 21261
    java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 273(offset:273).state:1427 androidx.recyclerview.widget.RecyclerView{101d0ef VFED..... .......D 0,0-1080,1151 #7f08018b app:id/rv_resources}, adapter:space.taran.arknavigator.ui.adapter.ResourcesRVAdapter@8eb1360, layout:androidx.recyclerview.widget.GridLayoutManager@83eb019, context:space.taran.arknavigator.ui.activity.MainActivity@b18147e
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6364)
        at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
        at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
        at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
        at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
        at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7403)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
2021-11-30 18:13:23.960 1458-5450/? W/ActivityTaskManager:   Force finishing activity space.taran.arknavigator/.ui.activity.MainActivity
2021-11-30 18:13:23.967 21261-21261/space.taran.arknavigator I/Process: Sending signal. PID: 21261 SIG: 9
2021-11-30 18:13:24.056 1458-2182/? W/InputDispatcher: channel 'acc3990 space.taran.arknavigator/space.taran.arknavigator.ui.activity.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
2021-11-30 18:13:24.056 1458-2182/? E/InputDispatcher: channel 'acc3990 space.taran.arknavigator/space.taran.arknavigator.ui.activity.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2021-11-30 18:13:24.079 1458-5438/? I/WindowManager: WIN DEATH: Window{acc3990 u0 space.taran.arknavigator/space.taran.arknavigator.ui.activity.MainActivity}
2021-11-30 18:13:24.080 1458-5438/? W/InputDispatcher: Attempted to unregister already unregistered input channel 'acc3990 space.taran.arknavigator/space.taran.arknavigator.ui.activity.MainActivity (server)'
2021-11-30 18:13:24.083 1458-1495/? I/ActivityManager: Process space.taran.arknavigator (pid 21261) has died: vis+99 TOP 
2021-11-30 18:13:24.461 1458-1896/? W/ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{f3285be u0 space.taran.arknavigator/.ui.activity.MainActivity t-1 f}
2021-11-30 18:13:25.944 1458-1458/? W/NotificationService: Object died trying to hide notification android.app.ITransientNotification$Stub$Proxy@d32eb53 in package space.taran.arknavigator
```

**Comment by kirillt** [comment]
Good catch @vedranqa

**Comment by kirillt** [comment]
@vedranqa could you make a video of it and steps to reproduce?
If I scroll resource grid, I can't reproduce it.

**Comment by vedranqa** [comment]
Here is the video of reproduction:

https://user-images.githubusercontent.com/60543054/147671267-b249c071-2861-40ae-bc85-d2ab5714d6b8.mp4

[crashLog.txt](https://github.com/ARK-Builders/ARK-Navigator/files/7789235/crashLog.txt)

**Comment by kirillt** [comment]
Can't be reproduced anymore.
