### ISSUE TITLE
Removing folder inside root crash app

### ISSUE THREAD

**Issue by vedranqa** [ARK-Builders/ARK-Navigator#151]
Removing folder in root folder, crash app

steps to reproduce: 
Create root folder with other folders insde (folder1, folder2, folder3)
App will generate previews and other things for each file
Remove folder2 thru pc or other file browser
Open app, app will crash

**log:** 
2021-12-03 21:21:15.406 11200-11240/space.taran.arknavigator D/resources-index: 26 resources returned
2021-12-03 21:21:15.406 11200-11240/space.taran.arknavigator D/tags-storage: lostResources: [3784491444]
2021-12-03 21:21:15.422 11200-11200/space.taran.arknavigator E/AndroidRuntime: FATAL EXCEPTION: main
    Process: space.taran.arknavigator, PID: 11200
    java.lang.AssertionError: Index lost resources
        at space.taran.arknavigator.mvp.model.repo.tags.PlainTagsStorage$Companion$provide$2.invokeSuspend(PlainTagsStorage.kt:214)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2021-12-03 21:21:15.424 1783-3997/? W/ActivityTaskManager:   Force finishing activity space.taran.arknavigator/.ui.activity.MainActivity
2021-12-03 21:21:15.433 11200-11200/space.taran.arknavigator I/Process: Sending signal. PID: 11200 SIG: 9
2021-12-03 21:21:15.459 1783-2200/? W/InputDispatcher: channel 'c4414bf space.taran.arknavigator/space.taran.arknavigator.ui.activity.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
2021-12-03 21:21:15.459 1783-2200/? E/InputDispatcher: channel 'c4414bf space.taran.arknavigator/space.taran.arknavigator.ui.activity.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2021-12-03 21:21:15.461 1783-8215/? I/WindowManager: WIN DEATH: Window{c4414bf u0 space.taran.arknavigator/space.taran.arknavigator.ui.activity.MainActivity}
2021-12-03 21:21:15.461 1783-4683/? I/ActivityManager: Process space.taran.arknavigator (pid 11200) has died: fore TOP 
2021-12-03 21:21:15.461 1783-8215/? W/InputDispatcher: Attempted to unregister already unregistered input channel 'c4414bf space.taran.arknavigator/space.taran.arknavigator.ui.activity.MainActivity (server)'
2021-12-03 21:21:15.925 1783-2004/? W/ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{cc1a832 u0 space.taran.arknavigator/.ui.activity.MainActivity t-1 f}

**Comment by kirillt** [comment]
@vedranqa does it crash on this device when a file in the root removed? Or only deletion of folders cause this?

**Comment by kirillt** [comment]
Might be similar: https://github.com/ARK-Builders/ARK-Navigator/issues/76

**Comment by vedranqa** [comment]
in my case ios only happens when folder is removed,

**Comment by shakeebularsalan** [comment]
@kirillt, Verification done using APK file of 21 Oct 2023 in Samsung Galaxy S10+ (Android Version 12) and issue is not replicating.
