### ISSUE TITLE
Crash app because tag

### ISSUE THREAD

**Issue by vedranqa** [ARK-Builders/ARK-Navigator#168]
Adding or removing tag on photo crash app
details in log

Xiaomi A2
Android 10
Build 208
[taglog.txt](https://github.com/ARK-Builders/ARK-Navigator/files/7764961/taglog.txt)

**Comment by kirillt** [comment]
@vedranqa we need more details about how to reproduce, video would be really big help.

Also, are you sure this log is about tags?
```
    java.lang.RuntimeException: Canvas: trying to draw too large(399602368bytes) bitmap.
        at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:280)
        at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
        at android.widget.ImageView.onDraw(ImageView.java:1434)
        at com.ortiz.touchview.TouchImageView.onDraw(TouchImageView.kt:276)
        at android.view.View.draw(View.java:21440)
```
This looks more like #139.

**Comment by vedranqa** [comment]
Didn't reproduce now. Will check other versions.

**Comment by vedranqa** [comment]
will resolve this, can't reproduce now
