### ISSUE TITLE
Deleting few photos in row kills app

### ISSUE THREAD

**Issue by vedranqa** [ARK-Builders/ARK-Navigator#184]
Deleting few photos in row kills app

Steps to reproduce:

- Open photo
- Delete photo and delete few next opened by preview

```2022-01-12 21:17:00.054 10848-10848/space.taran.arknavigator D/images: loading image null
2022-01-12 21:17:00.056 10848-10848/space.taran.arknavigator D/resources-screen: binding view for resource 3544840671
2022-01-12 21:17:00.057 10848-10848/space.taran.arknavigator D/images: loading image /data/user/0/space.taran.arknavigator/cache/thumbnails/3544840671
2022-01-12 21:17:00.060 10848-10848/space.taran.arknavigator D/resources-screen: binding view for resource 2235889872
2022-01-12 21:17:00.061 10848-10848/space.taran.arknavigator D/images: loading image /data/user/0/space.taran.arknavigator/cache/thumbnails/2235889872
2022-01-12 21:17:00.070 10848-10848/space.taran.arknavigator D/resources-screen: binding view for resource 1117893274
2022-01-12 21:17:00.070 10848-10848/space.taran.arknavigator D/images: loading image /data/user/0/space.taran.arknavigator/cache/thumbnails/1117893274
2022-01-12 21:17:00.077 10848-10848/space.taran.arknavigator D/resources-screen: binding view for resource 3688767994
2022-01-12 21:17:00.077 10848-10848/space.taran.arknavigator D/images: loading image /data/user/0/space.taran.arknavigator/cache/thumbnails/3688767994
2022-01-12 21:17:00.083 10848-10848/space.taran.arknavigator D/resources-screen: binding view for resource 3938785865
2022-01-12 21:17:00.084 10848-10848/space.taran.arknavigator D/images: loading image /data/user/0/space.taran.arknavigator/cache/thumbnails/3938785865
2022-01-12 21:17:00.089 10848-10848/space.taran.arknavigator D/resources-screen: binding view for resource 3488986038
2022-01-12 21:17:00.089 10848-10848/space.taran.arknavigator D/images: loading image /data/user/0/space.taran.arknavigator/cache/thumbnails/3488986038
2022-01-12 21:17:00.096 10848-10848/space.taran.arknavigator D/resources-screen: binding view for resource 2764356699
2022-01-12 21:17:00.097 10848-10848/space.taran.arknavigator D/images: loading image /data/user/0/space.taran.arknavigator/cache/thumbnails/2764356699
2022-01-12 21:17:00.103 10848-10848/space.taran.arknavigator D/resources-screen: binding view for resource 1575614125
2022-01-12 21:17:00.103 10848-10848/space.taran.arknavigator D/images: loading image /data/user/0/space.taran.arknavigator/cache/thumbnails/1575614125
2022-01-12 21:17:00.125 10848-10848/space.taran.arknavigator W/Glide: Load failed for null with size [0x0]
    class com.bumptech.glide.load.engine.GlideException: Received null model
2022-01-12 21:17:00.875 10848-10848/space.taran.arknavigator D/gallery-screen: [remove_resource] clicked at position 8
2022-01-12 21:17:00.875 10848-10848/space.taran.arknavigator D/gallery-screen: deleting resource 1700916449
2022-01-12 21:17:00.876 10848-10935/space.taran.arknavigator D/tags-storage: forgetting resource 1700916449
2022-01-12 21:17:00.905 10848-10848/space.taran.arknavigator E/AndroidRuntime: FATAL EXCEPTION: main
    Process: space.taran.arknavigator, PID: 10848
    java.lang.AssertionError: At least one of shards must yield success
        at space.taran.arknavigator.mvp.model.repo.index.AggregatedResourcesIndex.tryShards(AggregatedResourcesIndex.kt:31)
        at space.taran.arknavigator.mvp.model.repo.index.AggregatedResourcesIndex.remove(AggregatedResourcesIndex.kt:21)
        at space.taran.arknavigator.mvp.presenter.GalleryPresenter.deleteResource(GalleryPresenter.kt:159)
        at space.taran.arknavigator.mvp.presenter.GalleryPresenter.access$deleteResource(GalleryPresenter.kt:29)
        at space.taran.arknavigator.mvp.presenter.GalleryPresenter$deleteResource$1.invokeSuspend(Unknown Source:16)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2022-01-12 21:17:00.907 2059-4744/system_process W/ActivityTaskManager:   Force finishing activity space.taran.arknavigator/.ui.activity.MainActivity
2022-01-12 21:17:00.907 2059-10940/system_process I/DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
2022-01-12 21:17:00.908 2059-4744/system_process W/InputReader: Device has associated, but no associated display id.
2022-01-12 21:17:00.914 2059-2099/system_process W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
2022-01-12 21:17:00.914 2059-2099/system_process W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
2022-01-12 21:17:00.909 2059-4744/system_process I/chatty: uid=1000(system) Binder:2059_1B identical 8 lines
2022-01-12 21:17:00.909 2059-4744/system_process W/InputReader: Device has associated, but no associated display id.
2022-01-12 21:17:00.914 10848-10848/space.taran.arknavigator I/Process: Sending signal. PID: 10848 SIG: 9
2022-01-12 21:17:00.979 2059-2171/system_process W/InputDispatcher: channel 'a04deab space.taran.arknavigator/space.taran.arknavigator.ui.activity.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0xd
2022-01-12 21:17:00.980 2059-2171/system_process E/InputDispatcher: channel 'a04deab space.taran.arknavigator/space.taran.arknavigator.ui.activity.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2022-01-12 21:17:00.983 2059-2869/system_process I/ActivityManager: Process space.taran.arknavigator (pid 10848) has died: vis+99 TOP 
2022-01-12 21:17:00.985 2059-3598/system_process I/WindowManager: WIN DEATH: Window{a04deab u0 space.taran.arknavigator/space.taran.arknavigator.ui.activity.MainActivity}
```

App build 242
Xiaomi a2, Andorid 11
Emulator, Pixel 5, android 10

**Comment by mdrlzy** [comment]
Fixed in #189
