### ISSUE TITLE
Transaction too large

### ISSUE THREAD

**Issue by mdrlzy** [ARK-Builders/ARK-Navigator#336]
```
03-10 00:11:02.958 D/main    (27424): pausing MainActivity
03-10 00:11:03.096 E/JavaBinder(27424): !!! FAILED BINDER TRANSACTION !!!  (parcel size = 879808)
03-10 00:11:03.097 W/ActivityStopInfo(27424): Bundle stats:
03-10 00:11:03.097 W/ActivityStopInfo(27424):   android:viewHierarchyState [size=1632]
03-10 00:11:03.097 W/ActivityStopInfo(27424):     android:views [size=1584]
03-10 00:11:03.112 W/ActivityStopInfo(27424):   androidx.lifecycle.BundlableSavedStateRegistry.key [size=877236]
03-10 00:11:03.112 W/ActivityStopInfo(27424):     android:support:activity-result [size=2908]
03-10 00:11:03.112 W/ActivityStopInfo(27424):       KEY_COMPONENT_ACTIVITY_REGISTERED_KEYS [size=2192]
03-10 00:11:03.128 W/ActivityStopInfo(27424):     android:support:fragments [size=873952]
03-10 00:11:03.128 W/ActivityStopInfo(27424):       fragment_6194f1ca-5b9f-4e87-8e2e-5e5cd568cce1 [size=2520]
03-10 00:11:03.128 W/ActivityStopInfo(27424):         state [size=2488]
03-10 00:11:03.128 W/ActivityStopInfo(27424):       state [size=1396]
03-10 00:11:03.140 W/ActivityStopInfo(27424):       fragment_d976c0ad-b321-4fcf-a33b-01c4d8779942 [size=796736]
03-10 00:11:03.152 W/ActivityStopInfo(27424):         state [size=796704]
03-10 00:11:03.153 W/ActivityStopInfo(27424):       fragment_9d5b70d0-9955-4fdb-b670-1b50f4dd285c [size=72156]
03-10 00:11:03.154 W/ActivityStopInfo(27424):         state [size=72124]
03-10 00:11:03.154 W/ActivityStopInfo(27424): PersistableBundle stats:
03-10 00:11:03.154 W/ActivityStopInfo(27424):   [null]
03-10 00:11:03.154 D/AndroidRuntime(27424): Shutting down VM
--------- beginning of crash
03-10 00:11:03.155 E/AndroidRuntime(27424): FATAL EXCEPTION: main
03-10 00:11:03.155 E/AndroidRuntime(27424): Process: space.taran.arknavigator, PID: 27424
03-10 00:11:03.155 E/AndroidRuntime(27424): java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 879808 bytes
03-10 00:11:03.155 E/AndroidRuntime(27424): 	at android.app.ActivityClient.activityStopped(ActivityClient.java:87)
03-10 00:11:03.155 E/AndroidRuntime(27424): 	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
03-10 00:11:03.155 E/AndroidRuntime(27424): 	at android.os.Handler.handleCallback(Handler.java:938)
03-10 00:11:03.155 E/AndroidRuntime(27424): 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-10 00:11:03.155 E/AndroidRuntime(27424): 	at android.os.Looper.loopOnce(Looper.java:201)
03-10 00:11:03.155 E/AndroidRuntime(27424): 	at android.os.Looper.loop(Looper.java:288)
03-10 00:11:03.155 E/AndroidRuntime(27424): 	at android.app.ActivityThread.main(ActivityThread.java:7870)
03-10 00:11:03.155 E/AndroidRuntime(27424): 	at java.lang.reflect.Method.invoke(Native Method)
03-10 00:11:03.155 E/AndroidRuntime(27424): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
03-10 00:11:03.155 E/AndroidRuntime(27424): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
03-10 00:11:03.155 E/AndroidRuntime(27424): Caused by: android.os.TransactionTooLargeException: data parcel size 879808 bytes
03-10 00:11:03.155 E/AndroidRuntime(27424): 	at android.os.BinderProxy.transactNative(Native Method)
03-10 00:11:03.155 E/AndroidRuntime(27424): 	at android.os.BinderProxy.transact(BinderProxy.java:571)
03-10 00:11:03.155 E/AndroidRuntime(27424): 	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1315)
03-10 00:11:03.155 E/AndroidRuntime(27424): 	at android.app.ActivityClient.activityStopped(ActivityClient.java:84)
03-10 00:11:03.155 E/AndroidRuntime(27424): 	... 9 more
```

**Comment by kirillt** [comment]
This bug happens really often: http://65.21.4.137:8080/app/1/bug/147/report
