### ISSUE TITLE
IndexOutOfBoundsException: Inconsistency detected

### ISSUE THREAD

**Issue by kirillt** [ARK-Builders/ARK-Navigator#340]
http://65.21.4.137:8080/app/1/bug/198/report
```
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionFileItemViewHolder{ac6343e position=922 id=-1, oldPos=-1, pLpos:-1 scrap [attachedScrap] tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{ed03169 VFED..... ......ID 0,147-1440,1961 #7f0901ee app:id/rv_resources}, adapter:space.taran.arknavigator.ui.adapter.ResourcesRVAdapter@de937ee, layout:androidx.recyclerview.widget.GridLayoutManager@b6b848f, context:space.taran.arknavigator.ui.activity.MainActivity@796c7a9
	at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:6156)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6339)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:572)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
	at android.view.View.layout(View.java:23203)
```

**Comment by ShubertMunthali** [comment]
We can reproduce this bug by scrolling resources and then switching tags before the scroll rests, in this way the app always crashes with this exception. It seems resources adapter binds the resources before selection changes as such it calculates item positions using the wrong number of selection. This comes from where grid selection is updated https://github.com/ARK-Builders/ARK-Navigator/blob/56e01cbc32a79fd593e32b8c6fb7df5a8ad18fef/app/src/main/java/space/taran/arknavigator/mvp/presenter/adapter/ResourcesGridPresenter.kt#L193-L202

**Comment by mdrlzy** [comment]
> From this script, seems updateAdapter is called before Dispatchers.Default finishes updating selection

It runs sequentially

Problem is that we change selection during scroll, as you said.
Maybe we need to stop scroll and block it while we change selection

**Comment by ShubertMunthali** [comment]
> 

Sure
