### ISSUE TITLE
No generators found during preview generation

### ISSUE THREAD

**Issue by kirillt** [ARK-Builders/ARK-Navigator#368]
1) Open a folder with MP3 file.
2) Wait until Resource Grid is loaded.
3) Crash:

```
java.lang.IllegalArgumentException: No generators found for /storage/emulated/0/Reading/518454945-80000-hours-hilary-greaves-global-priorities-institute.mp3
	at space.taran.arklib.domain.meta.MetadataGenerator$Companion.generate-gIAlu-s(MetadataGenerator.kt:35)
	at space.taran.arklib.domain.meta.RootMetadataStorage.generate(RootMetadataStorage.kt:89)
	at space.taran.arklib.domain.meta.RootMetadataStorage.access$generate(RootMetadataStorage.kt:21)
	at space.taran.arklib.domain.meta.RootMetadataStorage$generate$1$jobs$1$1.invokeSuspend(RootMetadataStorage.kt:73)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
```

**Comment by kirillt** [comment]
Also, we have the same error message for the case of missing metadata extractor.

**Comment by kirillt** [comment]
Same with `res` files:
```
java.lang.IllegalArgumentException: No generators found for /storage/emulated/0/Projects
/ARK/similarity/dssim/run.sh.res
	at space.taran.arklib.domain.meta.MetadataGenerator$Companion.generate-gIAlu-s(MetadataGenerator.kt:35)
	at space.taran.arklib.domain.meta.RootMetadataStorage.generate(RootMetadataStorage.kt:89)
	at space.taran.arklib.domain.meta.RootMetadataStorage.access$generate(RootMetadataStorage.kt:21)
	at space.taran.arklib.domain.meta.RootMetadataStorage$generate$1$jobs$1$1.invokeSuspend(RootMetadataStorage.kt:73)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/xml/stream/XMLResolver;
		at org.apache.tika.utils.XMLReaderUtils.parseSAX(XMLReaderUtils.java:472)
		at org.apache.tika.detect.XmlRootExtractor.extractRootElement(XmlRootExtractor.java:73)
		at org.apache.tika.detect.XmlRootExtractor.extractRootElement(XmlRootExtractor.java:46)
		at org.apache.tika.mime.MimeTypes.getMimeType(MimeTypes.java:252)
		at org.apache.tika.mime.MimeTypes.detect(MimeTypes.java:523)
		at org.apache.tika.detect.CompositeDetector.detect(CompositeDetector.java:85)
		at org.apache.tika.Tika.detect(Tika.java:160)
		at org.apache.tika.Tika.detect(Tika.java:204)
		at space.taran.arklib.utils.FileUtilsKt.detectMimeType(FileUtils.kt:21)
		at space.taran.arklib.domain.meta.MetadataGenerator$DefaultImpls.isValid(MetadataGenerator.kt:25)
		at space.taran.arklib.domain.meta.generator.ImageMetadataGenerator.isValid(ImageMetadataGenerator.kt:8)
		at space.taran.arklib.domain.meta.MetadataGenerator$Companion.generate-gIAlu-s(MetadataGenerator.kt:32)
		... 11 more
	Caused by: java.lang.ClassNotFoundException: javax.xml.stream.XMLResolver
		... 23 more
	Suppressed: java.lang.IllegalArgumentException: No generators found for /storage/emulated/0/Projects/ARK/similarity/dssim/run.sh
		... 12 more
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@dec0a84, Dispatchers.IO]
```
