### ISSUE TITLE
Crash during root opening

### ISSUE THREAD

**Issue by kirillt** [ARK-Builders/ARK-Navigator#377]
http://65.21.4.137:8080/app/1/bug/254/report/35fc568e-0f72-45c6-a182-783d832bc0d0

```
ava.lang.ClassCastException: java.util.LinkedHashMap$LinkedHashMapEntry cannot be cast to java.util.HashMap$TreeNode
  at java.util.HashMap$TreeNode.moveRootToFront(HashMap.java:1831)
  at java.util.HashMap$TreeNode.treeify(HashMap.java:1948)
  at java.util.HashMap.treeifyBin(HashMap.java:771)
  at java.util.HashMap.putVal(HashMap.java:643)
  at java.util.HashMap.put(HashMap.java:611)
  at space.taran.arklib.domain.storage.FolderStorage$readFromDisk$jobs$2$1.invokeSuspend(FolderStorage.kt:100)
```

**Comment by kirillt** [comment]
Fixed in the lib: https://github.com/ARK-Builders/arklib-android/pull/84/files
