### ISSUE TITLE
UninitializedPropertyAccessException crash when browsing device folders

### ISSUE THREAD

**Issue by tuancoltech** [ARK-Builders/ARK-Navigator#389]
```
2023-10-09 22:41:03.268 16044-16044 AndroidRuntime          dev.arkbuilders.navigator            E  FATAL EXCEPTION: main
                                                                                                    Process: dev.arkbuilders.navigator, PID: 16044
                                                                                                    kotlin.UninitializedPropertyAccessException: lateinit property animator has not been initialized
                                                                                                    	at space.taran.arkfilepicker.presentation.folderstree.DeviceFolderItem.animateExpanded(FolderItemView.kt:63)
                                                                                                    	at space.taran.arkfilepicker.presentation.folderstree.DeviceFolderItem.bindView$lambda-4$lambda-3(FolderItemView.kt:56)
                                                                                                    	at space.taran.arkfilepicker.presentation.folderstree.DeviceFolderItem.$r8$lambda$8FcsGw0SvGESLOfC79jMD7sUeaE(Unknown Source:0)
                                                                                                    	at space.taran.arkfilepicker.presentation.folderstree.DeviceFolderItem$$ExternalSyntheticLambda1.onClick(Unknown Source:2)
                                                                                                    	at android.view.View.performClick(View.java:7441)
                                                                                                    	at android.view.View.performClickInternal(View.java:7418)
                                                                                                    	at android.view.View.access$3700(View.java:835)
                                                                                                    	at android.view.View$PerformClick.run(View.java:28676)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7842)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```

Steps:
- Go to `Manage Folder`
- Try adding `ROOT` folder (if already added, choose an arbitrary folder)
- Click on the memory card icon.

Repeat above steps several times -> Crash.

**Comment by tuancoltech** [comment]
Created issue in `filepicker` repository: https://github.com/ARK-Builders/ark-filepicker/issues/26.
Hence, closing this.
