### ISSUE TITLE
Tags storage access in coroutine

### ISSUE THREAD

**Issue by kirillt** [ARK-Builders/ARK-Navigator#43]
```
D/item-container: item 8 clicked
D/gallery-screen: preview at 8 clicked, switching controls on/off
E/: [ZeroHung]zrhung_get_config: Get config failed for wp[0x0102]
D/gallery-screen: tag todo on resource 1771473116 long-clicked
D/gallery-screen: closing dialog in GalleryFragment
D/gallery-screen: displaying tags of resource 1771473116 for preview
D/gallery-screen: displaying tags resource 1771473116 for edit
D/OpenGLRenderer:   HWUI Binary is  enabled
E/: [ZeroHung]zrhung_get_config: Get config failed for wp[0x0102]
D/gallery-screen: tags [ark] added to 1771473116
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/OpenGLRenderer:   HWUI Binary is  enabled
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: space.taran.arknavigator, PID: 13324
    java.lang.AssertionError: Storage isn't aware about this resource id
        at space.taran.arknavigator.mvp.model.repo.PlainTagsStorage$setTags$2.invokeSuspend(PlainTagsStorage.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by mdrlzy** [comment]
I think this bug is not due to coroutines. How to reproduce:
1. Open the resource screen via the bottom navigation
2. Open resource
3. Set tag
