### ISSUE TITLE
Access denied on Android 11

### ISSUE THREAD

**Issue by kirillt** [ARK-Builders/ARK-Navigator#85]
Android 11, internal storage (no SD-card at all). Crash during opening (navigating to) any folder:
```
D/tags-storage: file /storage/emulated/0/Pictures/.ark-tags exists, last modified at 2021-09-27T21:58:35Z
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: space.taran.arknavigator, PID: 30437
    java.nio.file.AccessDeniedException: /storage/emulated/0/Pictures/.ark-tags
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
        at java.nio.file.Files.newInputStream(Files.java:152)
        at java.nio.file.Files.newBufferedReader(Files.java:2784)
        at java.nio.file.Files.readAllLines(Files.java:3202)
        at space.taran.arknavigator.mvp.model.repo.PlainTagsStorage$readStorage$2.invokeSuspend(PlainTagsStorage.kt:154)
```

**Comment by kirillt** [comment]
Fixed a44a12c76430a2831b9d1986b85ff3baedc52c3e
