### ISSUE TITLE
App crashes when same folder is added twice as Favorite

### ISSUE THREAD

**Issue by melvin4u445** [ARK-Builders/ARK-Navigator#89]
**Steps:**
1. Add a folder as root (DCIM, for example)
2. Add one of its subfolder as a Favorite (DCIM/Camera for example)
3. Add the same folder again as Favorite
App crashes

**Crash log:**
```
--------- beginning of crash
10-03 20:36:00.271  2032  2032 E AndroidRuntime: FATAL EXCEPTION: main
10-03 20:36:00.271  2032  2032 E AndroidRuntime: Process: space.taran.arknavigator, PID: 2032
10-03 20:36:00.271  2032  2032 E AndroidRuntime: java.lang.AssertionError: Path must be checked in RootPicker
10-03 20:36:00.271  2032  2032 E AndroidRuntime: 	at space.taran.arknavigator.mvp.presenter.FoldersPresenter$addFavorite$1.invokeSuspend(FoldersPresenter.kt:181)
10-03 20:36:00.271  2032  2032 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
10-03 20:36:00.271  2032  2032 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
10-03 20:36:00.271  2032  2032 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
10-03 20:36:00.271  2032  2032 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-03 20:36:00.271  2032  2032 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:216)
10-03 20:36:00.271  2032  2032 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7211)
10-03 20:36:00.271  2032  2032 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-03 20:36:00.271  2032  2032 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
10-03 20:36:00.271  2032  2032 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
10-03 20:36:00.297  2032  2032 I Process : Sending signal. PID: 2032 SIG: 9
```

**Comment by melvin4u445** [comment]
Cannot reproduce this now. Looks good

**Comment by kirillt** [comment]
@melvin4u445 don't close please until it's merged into `main` branch.

**Comment by kirillt** [comment]
Merged now.
